from django.db import models

from django.contrib.auth.models import User
# Create your models here.
class cv(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    name=models.CharField(max_length=100)
    image=models.ImageField(upload_to='media')
    ability=models.CharField(max_length=100)
    dob=models.DateField()
    mobile=models.CharField(max_length=14)
    email=models.EmailField(max_length=250)
    github_id=models.CharField(max_length=250)
    linkedin_id=models.CharField(max_length=250)
    address=models.CharField(max_length=50)
    years_degree=models.CharField(max_length=15,null=True, blank=True)
    name_degree=models.CharField(max_length=30,null=True, blank=True)
    clg_name=models.CharField(max_length=100,null=True, blank=True)
    year12th=models.CharField(max_length=15,null=True, blank=True)
    class_name12th=models.CharField(max_length=10,null=True, blank=True)
    school_name12th=models.CharField(max_length=100,null=True, blank=True)
    year10th=models.CharField(max_length=15,null=True, blank=True)
    class_name10th=models.CharField(max_length=10,null=True, blank=True)
    school_name10th=models.CharField(max_length=100,null=True, blank=True)
    language=models.CharField(max_length=200,null=True, blank=True)
    about_para=models.CharField(max_length=500,null=True, blank=True)
    working_years_1=models.CharField(max_length=50,null=True, blank=True)
    company_name_1=models.CharField(max_length=50,null=True, blank=True)
    designation_1=models.CharField(max_length=50,null=True, blank=True)
    about_1=models.CharField(max_length=250,null=True, blank=True)
    working_years_2=models.CharField(max_length=50,null=True, blank=True)
    company_name_2=models.CharField(max_length=50,null=True, blank=True)
    designation_2=models.CharField(max_length=50,null=True, blank=True)
    about_2=models.CharField(max_length=250,null=True, blank=True)
    skill=models.CharField(max_length=200,null=True, blank=True)
    in_percent=models.CharField(max_length=50,null=True, blank=True)
    interest=models.CharField(max_length=200,null=True, blank=True)