# Generated by Django 4.2.4 on 2023-09-15 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0002_rename_para_1_cv_about_para_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='percentage',
            new_name='in_percent',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='skill_in_percent',
            new_name='in_percentage',
        ),
    ]
