# Generated by Django 4.2.4 on 2023-09-16 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0003_rename_percentage_cv_in_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='in_percentage',
        ),
    ]
