# Generated by Django 4.2.4 on 2023-09-16 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0004_remove_cv_in_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='in_percent',
        ),
    ]
