# Generated by Django 4.2.4 on 2023-09-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='strem',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
