# Generated by Django 4.2.4 on 2023-09-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_rename_student_details_student_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_detail',
            name='city',
        ),
        migrations.RemoveField(
            model_name='student_detail',
            name='state',
        ),
        migrations.AlterField(
            model_name='student_detail',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student_detail',
            name='pin_code',
            field=models.IntegerField(),
        ),
    ]
